/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author REN
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        mnBarang = new javax.swing.JMenuItem();
        mnKonsumen = new javax.swing.JMenuItem();
        mnPemasok = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnTransJual = new javax.swing.JMenuItem();
        mnTransBeli = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnLapJual = new javax.swing.JMenuItem();
        mnLapBeli = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mnBackData = new javax.swing.JMenuItem();
        mnKeluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu6.setText("Data Master");

        mnBarang.setText("Data Barang");
        mnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBarangActionPerformed(evt);
            }
        });
        jMenu6.add(mnBarang);

        mnKonsumen.setText("Data Konsumen");
        mnKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKonsumenActionPerformed(evt);
            }
        });
        jMenu6.add(mnKonsumen);

        mnPemasok.setText("Data Pemasok");
        mnPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPemasokActionPerformed(evt);
            }
        });
        jMenu6.add(mnPemasok);

        jMenuBar2.add(jMenu6);

        jMenu3.setText("Transaksi");

        mnTransJual.setText("Transaksi Jual");
        mnTransJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransJualActionPerformed(evt);
            }
        });
        jMenu3.add(mnTransJual);

        mnTransBeli.setText("Transaksi Beli");
        mnTransBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransBeliActionPerformed(evt);
            }
        });
        jMenu3.add(mnTransBeli);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Laporan");

        mnLapJual.setText("Laporan Penjualan");
        mnLapJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapJualActionPerformed(evt);
            }
        });
        jMenu4.add(mnLapJual);

        mnLapBeli.setText("Laporan Pembelian");
        mnLapBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapBeliActionPerformed(evt);
            }
        });
        jMenu4.add(mnLapBeli);

        jMenuBar2.add(jMenu4);

        jMenu7.setText("Utility");

        mnBackData.setText("Backup Database");
        mnBackData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBackDataActionPerformed(evt);
            }
        });
        jMenu7.add(mnBackData);

        jMenuBar2.add(jMenu7);

        mnKeluar.setText("Keluar");
        mnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnKeluarMouseClicked(evt);
            }
        });
        jMenuBar2.add(mnKeluar);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnKeluarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnKeluarMouseClicked

    private void mnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBarangActionPerformed
        // TODO add your handling code here:
        new frmBarang().setVisible(true);
    }//GEN-LAST:event_mnBarangActionPerformed

    private void mnKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKonsumenActionPerformed
        // TODO add your handling code here:
        new frmKonsumen().setVisible(true);
    }//GEN-LAST:event_mnKonsumenActionPerformed

    private void mnTransJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransJualActionPerformed
        // TODO add your handling code here:
        new frmTransaksi().setVisible(true);
    }//GEN-LAST:event_mnTransJualActionPerformed

    private void mnTransBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransBeliActionPerformed
        // TODO add your handling code here:
        new frmTransBeli().setVisible(true);
    }//GEN-LAST:event_mnTransBeliActionPerformed

    private void mnLapJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapJualActionPerformed
        // TODO add your handling code here:
        new LapPenjualan().setVisible(true);
    }//GEN-LAST:event_mnLapJualActionPerformed

    private void mnBackDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBackDataActionPerformed
        // TODO add your handling code here:
        new frmBackupSql().setVisible(true);
    }//GEN-LAST:event_mnBackDataActionPerformed

    private void mnPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPemasokActionPerformed
        // TODO add your handling code here:
        new frmPemasok().setVisible(true);
    }//GEN-LAST:event_mnPemasokActionPerformed

    private void mnLapBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapBeliActionPerformed
        // TODO add your handling code here:
        new LapPembelian().setVisible(true);
    }//GEN-LAST:event_mnLapBeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem mnBackData;
    private javax.swing.JMenuItem mnBarang;
    private javax.swing.JMenu mnKeluar;
    private javax.swing.JMenuItem mnKonsumen;
    private javax.swing.JMenuItem mnLapBeli;
    private javax.swing.JMenuItem mnLapJual;
    private javax.swing.JMenuItem mnPemasok;
    private javax.swing.JMenuItem mnTransBeli;
    private javax.swing.JMenuItem mnTransJual;
    // End of variables declaration//GEN-END:variables
}
